// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslm2IOA5OEmGac9eFRIrSh8OY2gSuclw',
    appId: '1:399592873856:web:739a1669fca3f61c66eb65',
    messagingSenderId: '399592873856',
    projectId: 'fp-tekber-kel4-notes-new',
    authDomain: 'fp-tekber-kel4-notes-new.firebaseapp.com',
    storageBucket: 'fp-tekber-kel4-notes-new.firebasestorage.app',
    measurementId: 'G-030PHH0YJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPj4Io3IpbWRTXiUJoPeWUxKnQhQ75Qg',
    appId: '1:399592873856:android:f56ecb82c62c213466eb65',
    messagingSenderId: '399592873856',
    projectId: 'fp-tekber-kel4-notes-new',
    storageBucket: 'fp-tekber-kel4-notes-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGtGOMknochyyJZ3MGQujXIqFH3uTvuI',
    appId: '1:399592873856:ios:fe44a36ab24a079a66eb65',
    messagingSenderId: '399592873856',
    projectId: 'fp-tekber-kel4-notes-new',
    storageBucket: 'fp-tekber-kel4-notes-new.firebasestorage.app',
    iosBundleId: 'com.example.fpTekberKel4Notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDppnKD7JUHyyEPG7aRjiJsyBlU1WQFZM8',
    appId: '1:1033476911060:ios:7b8e2fd221bc31a0adb041',
    messagingSenderId: '1033476911060',
    projectId: 'fp-tekber-kel4-notes',
    storageBucket: 'fp-tekber-kel4-notes.firebasestorage.app',
    iosBundleId: 'com.example.fpTekberKel4Notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsXrte4khG5iHEv0vmCNWnqzyWe1-XIAQ',
    appId: '1:1033476911060:web:41f814154ec8285badb041',
    messagingSenderId: '1033476911060',
    projectId: 'fp-tekber-kel4-notes',
    authDomain: 'fp-tekber-kel4-notes.firebaseapp.com',
    storageBucket: 'fp-tekber-kel4-notes.firebasestorage.app',
    measurementId: 'G-5WFCG68TYS',
  );

}